################################################################################
# general ######################################################################
################################################################################

# Keep pinentry windows focused
windowrule = stay_focused on, match:class ^(pinentry-)

# Float specific apps
windowrule = float on, match:class ^(pavucontrol)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule = float on, match:title ^(btop)$

# Example windowrule
# windowrule = float, match:class ^(kitty)$, match:title ^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/

# Disabled due to lag when switching to transparent Firefox
# windowrule = opacity 0.9 0.9, match:class ^(firefox)$

################################################################################
### dropdown (thx contre) ######################################################
################################################################################

windowrule = no_anim on, match:class ^(dropdown)$
windowrule = move 15% -30, match:class ^(dropdown)$
windowrule = size 70% 40%, match:class ^(dropdown)$
windowrule = float on, match:class ^(dropdown)$

################################################################################
### screen sharing #############################################################
################################################################################

windowrule = opacity 0.0 override 0.0 override, match:class ^(xwaylandvideobridge)$
windowrule = no_anim on, match:class ^(xwaylandvideobridge)$
windowrule = no_focus on, match:class ^(xwaylandvideobridge)$
windowrule = no_initial_focus on, match:class ^(xwaylandvideobridge)$

################################################################################
# steam ########################################################################
################################################################################

windowrule = stay_focused on, match:title ^()$, match:class ^(steam)$
windowrule = min_size 1 1, match:title ^()$, match:class ^(steam)$
