import = [] # you can import other files

[default_session]
startup_command = "nvim -c ':lua require(\"telescope.builtin\").find_files({ hidden = true, no_ignore = true, })'"

# [[session]]
# name = "nix"
# path = "~/nix"
# startup_script =  "~/.config/sesh/scripts/splitTelescope.sh"
